package company.com.mybatis.dao;

import company.com.mybatis.model.Tasks;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TASKS
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TASKS
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    int insert(Tasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TASKS
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    Tasks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TASKS
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    List<Tasks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TASKS
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    int updateByPrimaryKey(Tasks record);
}