package company.com.mybatis.dao;

import company.com.mybatis.model.WorkerTask;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface WorkerTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER_TASK
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    int insert(WorkerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WORKER_TASK
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    List<WorkerTask> selectAll();
}