package company.com.mybatis.model;

public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKS.ABBREVIATION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String abbreviation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKS.IDENTIFIER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKS.TITLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKS.ID
     *
     * @return the value of PUBLIC.TASKS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKS.ID
     *
     * @param id the value for PUBLIC.TASKS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKS.ABBREVIATION
     *
     * @return the value of PUBLIC.TASKS.ABBREVIATION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKS.ABBREVIATION
     *
     * @param abbreviation the value for PUBLIC.TASKS.ABBREVIATION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKS.DESCRIPTION
     *
     * @return the value of PUBLIC.TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKS.DESCRIPTION
     *
     * @param description the value for PUBLIC.TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKS.IDENTIFIER
     *
     * @return the value of PUBLIC.TASKS.IDENTIFIER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKS.IDENTIFIER
     *
     * @param identifier the value for PUBLIC.TASKS.IDENTIFIER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKS.TITLE
     *
     * @return the value of PUBLIC.TASKS.TITLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKS.TITLE
     *
     * @param title the value for PUBLIC.TASKS.TITLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}