package company.com.mybatis.model;

public class Workers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.BIRTH_DATE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.FIRST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.ISMANAGER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Boolean ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.PERSONAL_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String personalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.ROLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKERS.COMPANY_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.ID
     *
     * @return the value of PUBLIC.WORKERS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.ID
     *
     * @param id the value for PUBLIC.WORKERS.ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.BIRTH_DATE
     *
     * @return the value of PUBLIC.WORKERS.BIRTH_DATE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.BIRTH_DATE
     *
     * @param birthDate the value for PUBLIC.WORKERS.BIRTH_DATE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.FIRST_NAME
     *
     * @return the value of PUBLIC.WORKERS.FIRST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.WORKERS.FIRST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.ISMANAGER
     *
     * @return the value of PUBLIC.WORKERS.ISMANAGER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Boolean getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.ISMANAGER
     *
     * @param ismanager the value for PUBLIC.WORKERS.ISMANAGER
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setIsmanager(Boolean ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.LAST_NAME
     *
     * @return the value of PUBLIC.WORKERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.LAST_NAME
     *
     * @param lastName the value for PUBLIC.WORKERS.LAST_NAME
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.PERSONAL_ID
     *
     * @return the value of PUBLIC.WORKERS.PERSONAL_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.PERSONAL_ID
     *
     * @param personalId the value for PUBLIC.WORKERS.PERSONAL_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setPersonalId(String personalId) {
        this.personalId = personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.ROLE
     *
     * @return the value of PUBLIC.WORKERS.ROLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.ROLE
     *
     * @param role the value for PUBLIC.WORKERS.ROLE
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKERS.COMPANY_ID
     *
     * @return the value of PUBLIC.WORKERS.COMPANY_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKERS.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.WORKERS.COMPANY_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}