package company.com.mybatis.model;

public class WorkerTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKER_TASK.WORKERS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Integer workersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKER_TASK.TASKS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    private Integer tasksId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKER_TASK.WORKERS_ID
     *
     * @return the value of PUBLIC.WORKER_TASK.WORKERS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Integer getWorkersId() {
        return workersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKER_TASK.WORKERS_ID
     *
     * @param workersId the value for PUBLIC.WORKER_TASK.WORKERS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setWorkersId(Integer workersId) {
        this.workersId = workersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKER_TASK.TASKS_ID
     *
     * @return the value of PUBLIC.WORKER_TASK.TASKS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public Integer getTasksId() {
        return tasksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKER_TASK.TASKS_ID
     *
     * @param tasksId the value for PUBLIC.WORKER_TASK.TASKS_ID
     *
     * @mbg.generated Tue Apr 26 21:32:44 EEST 2022
     */
    public void setTasksId(Integer tasksId) {
        this.tasksId = tasksId;
    }
}